"""Monitoring API schemas."""

from .responses import (
    AlertListResponse,
    AlertResponse,
    ClusterDetailResponse,
    ClusterHealthResponse,
    ClusterListResponse,
    ClusterMetricsResponse,
    ClusterSummaryResponse,
    GPUUtilizationPointResponse,
    GPUUtilizationResponse,
    GrafanaDashboardInfo,
    GrafanaDashboardsResponse,
    InstanceGroupResponse,
    MetricDataPointResponse,
    MetricResponse,
    MetricSeriesResponse,
    NetworkMetricsResponse,
    NodeListResponse,
    NodeSummaryResponse,
    ResourceUtilizationResponse,
    StorageMetricsResponse,
)

__all__ = [
    "MetricDataPointResponse",
    "MetricResponse",
    "ClusterMetricsResponse",
    "GPUUtilizationPointResponse",
    "GPUUtilizationResponse",
    "GrafanaDashboardInfo",
    "GrafanaDashboardsResponse",
    "StorageMetricsResponse",
    "NetworkMetricsResponse",
    "ClusterHealthResponse",
    # 监控页响应 Schema（2C.1）
    "ClusterSummaryResponse",
    "ClusterListResponse",
    "InstanceGroupResponse",
    "ClusterDetailResponse",
    "NodeSummaryResponse",
    "NodeListResponse",
    "ResourceUtilizationResponse",
    "MetricSeriesResponse",
    "AlertResponse",
    "AlertListResponse",
]
